config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "homes#home"
  get "about" => "homes#about"

  get "search/keyword" => "searches#search_keyword"

  resources :post_learnings do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    get :search_genre, on: :collection
  end

  resources :post_learnings
  namespace :admin do
    resources :post_learnings, only: [:index, :new, :create, :show,  :edit, :destroy]
  end

  post "post_learnings/new" => "post_learnings#new"

  get "post_learnings/:id/post_comments" => "post_learnings#show"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  
  devise_scope :user do
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
    get "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  get 'users/follow_list/:user_id' =>'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'

  resources :tags, only: [:index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  resources :genres

  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]

  resources :notifications, only: [:index]  do
    collection do
      delete 'destroy_all'
    end
  end
  
  resources :activities, only: [:index] do 
    collection do
      delete 'destroy_all'
    end
  end
  
  resources :contacts, only: [:new, :create]
 
end

app/models/notification.rb
class Notification < ApplicationRecord
  default_scope -> { order(created_at: :desc) }
  belongs_to :post_learning, optional: true
  belongs_to :comment, optional: true
  belongs_to :room, optional: true
  belongs_to :message, optional: true
  
  belongs_to :visitor, class_name: 'User', foreign_key: 'visitor_id', optional: true
  belongs_to :visited, class_name: 'User', foreign_key: 'visited_id', optional: true
  
end

def create_notification_comment!(current_user, comment_id)
  # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
	temp_ids = Comment.select(:user_id).where(item_id: id).where.not(user_id: current_user.id).distinct
	temp_ids.each do |temp_id|
	   save_notification_comment!(current_user, comment_id, temp_id['user_id'])
  end
  # まだ誰もコメントしていない場合は、投稿者に通知を送る
  save_notification_comment!(current_user, comment_id, user_id) if temp_ids.blank?
end

def save_notification_comment!(current_user, comment_id, visited_id)
  # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
  notification = current_user.active_notifications.new(
    item_id: id,
    comment_id: comment_id,
    visited_id: visited_id,
    action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    if notification.visiter_id == notification.visited_id
      notification.checked = true
    end
    notification.save if notification.valid?
  end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @genres = Genre.all
    @notifications = current_user.passive_notifications.all.where.not(visitor_id: current_user.id).page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
    @genres = Genre.all
  end
  
  def destroy_all
    @notifications = current_user.passive_notifications.destroy_all
    flash[:notice] = "通知を削除しました"
  	redirect_to request.referer 
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def notification_form(notification)
	  @visiter = notification.visiter
	  @comment = nil
	  your_item = link_to 'あなたの投稿', users_item_path(notification), style:"font-weight: bold;"
	  @visiter_comment = notification.post_comment_id
	  #notification.actionがfollowかlikeかcommentか
	  case notification.action
	    when "follow" then
	      tag.a(notification.visiter.name, href:users_user_path(@visiter), style:"font-weight: bold;")+"があなたをフォローしました"
	    when "favorite" then
	      tag.a(notification.visiter.name, href:users_user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:users_item_path(notification.post_learning_id), style:"font-weight: bold;")+"にいいねしました"
	    when "post_comment" then
	    	@comment = PostComment.find_by(id: @visiter_comment)&.content
	    	tag.a(@visiter.name, href:users_user_path(@visiter), style:"font-weight: bold;")+"が"+tag.a('あなたの投稿', href:users_item_path(notification.post_learning_id), style:"font-weight: bold;")+"にコメントしました"
	    end
  	end
  	
  	def unchecked_notifications
    	current_user.passive_notifications.where(checked: false)
    end
    
    def unchecked_notifications_activity
      current_user.active_notifications.where(checked: false)
    end
end

app/views/notifications/_notification.html.erb
<% visitor = notification.visitor %>
<% visited = notification.visited %>

<div class="notification-text-time">
  <p>
    <%= time_ago_in_words(notification.created_at).upcase %>前
  </p>
</div>
<div class="notification-content">
  <div class="notification-left-name-image">
    <div class="notification-left-image">
      <%= link_to user_path(notification.visitor), class: "article-notification-image" do %>
        <%= image_tag visitor.get_profile_image(100,100) %>  
      <% end %>
    </div>
    <div class="notification-text-name">
      <%= link_to user_path(notification.visitor) do %>
        <strong>
          <%= visitor.name %>
        </strong>
      <% end %>
    </div>
  </div>
  <div class="notification-text-content">
    <% case notification.action
    when 'follow' %>
      <div class="notification-favorite-content-inner">
        さんがあなたを フォローしました
      </div>
    <% when 'favorite' %>
      <div class="notification-favorite-content-inner">
        さんが
        <strong>
          <%= link_to 'あなたの投稿', notification.post_learning %>
        </strong>
        にいいねしました
      </div>
    <% when 'post_comment' %>
      <% if notification.post_learning.user_id == visited.id %>
        <div class="notification-comment-my-content">
        　<strong><%= link_to "あなたの投稿", notification.post_learning %></strong> にコメントしました  
        </div>
      <% else %>  
        <div class="notification-comment-user-content">
          <div class=notification-comment-name-content>
            さんが
            <%= link_to post_learning_path(notification.post_learning), class: "article-notification-image" do %>
              <strong>
                <%= notification.post_learning.user.name %>
              </strong>
            <% end %>
            さんの投稿にコメントしました
          </div>
        </div>
      <% end %>
      <p class="notification-comment"><%= PostComment.find_by(id: notification.post_comment_id)&.comment %></p>
    <% when 'dm' %>
      <div class="notification-favorite-content-inner">
        さんがあなたにDMを送りました
      </div>
      <p class="notification-comment">
        <%= truncate(notification.message.body, length: 20, omission: '... (一部表示)') %>
        <%= link_to room_path(notification.room) do %>
          <h4 class="dm-move">DMの送信画面に移動</h4>
        <% end %>
      </p>
    <% end %>
  </div>
</div>
<hr>

app/views/notifications/index.html.erb
<div class="first-home-view">
  <%= render 'shared/header' %>
  <%= render 'shared/flash' %>
  <div class="result-notifications-main-full">
    <div class="result-notifications-name-title">
      <p>通知</p>
    </div>
  </div>
  <div class="top-contents">
    <aside class="sidebar_left">
      <%= render 'shared/sidebar_left' %>
    </aside>
    <article class="users-article">
      <div class="destroy_all_notifications">
        <%= link_to destroy_all_notifications_path, method: :delete do %>
          <h7>全削除</h7>
        <% end %>
      </div>
      <hr>
        <% if @notifications.present? %>
          <div class="users-index">
            <% @notifications.each do |notification| %>
              <%= render partial: 'notifications/notification', locals: {notification: notification} %>
              <%= paginate @notifications, class: "page" %>
            <% end %> 
          </div>
        <% else %>
          <p class="no-notification">通知はありません</p>
        <% end %>
    </article>
    <aside class="sidebar_right">
      <%= render 'shared/sidebar_right' %>
    </aside>
  </div>
</div>
<%= render 'shared/footer' %>