config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "homes#home"
  get "about" => "homes#about"

  get "search/keyword" => "searches#search_keyword"

  resources :post_learnings do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    get :search_genre, on: :collection
  end

  resources :post_learnings
  namespace :admin do
    resources :post_learnings, only: [:index, :new, :create, :show,  :edit, :destroy]
  end

  post "post_learnings/new" => "post_learnings#new"

  get "post_learnings/:id/post_comments" => "post_learnings#show"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  
  devise_scope :user do
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
    get "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  get 'users/follow_list/:user_id' =>'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'

  resources :tags, only: [:index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  resources :genres

  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]

  resources :notifications, only: [:index]  do
    collection do
      delete 'destroy_all'
    end
  end
  
  resources :activities, only: [:index] do 
    collection do
      delete 'destroy_all'
    end
  end
  
  resources :contacts, only: [:new, :create]
 
end

app/views/shared/_dm-btn.html.erb
<div class="chat-btn-content-inner-link">
  <% unless current_user.id == @user.id %>　
    <% if (current_user.following? @user) && (@user.following? current_user) %>
      <% if @isRoom == true %>
        <div class="chat-start-link">
          <a href="/rooms/<%= @roomId %>", class="home-link" >
            <%= image_tag asset_path('mail.png'), class:'icon chat-icon' %>
            <span>チャットへ</span>
          </a>    
        </div>
      <% else %>
        <div>
          <%= form_with model: @room do |f| %>
            <%= fields_for @entry do |e| %>
              <%= e.hidden_field :user_id, value: @user.id %>
            <% end %>
            <div class= "chat-btn-link" >
              <%= f.submit "チャットを始める" %>  
            </div>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div> 

app/views/shared/_dm.html.erb
<div class="room-full">
  <div class="user-name">
    <% @entries.each do |e| %>
      <div class="article-notification-image">
        <%= image_tag e.user.get_profile_image(100,100) %>  
      </div>
      <div class="article-chat-name-image">
        <a class="rooms-user-link" href="/users/<%= e.user.id %>">
          <%= e.user.name %>さん
        </a>
      </div>
    <% end %>
  </div>
  <div class="chats">
    <div class="chat">
      <% if @messages.present? %>
        <% @messages.reverse.each do |message| %>
          <div class="chat-profile-user-content">
            <div class="chat-user-profile">
              <div class="chat-user-image">
                <%= image_tag message.user.get_profile_image(100,100) %>  
              </div>
              <div class="chat-user-time">
                <p>
                  <a class="rooms-user-link" href="/users/<%= message.user.id %>">
                    <strong><%= message.user.name %></strong>
                  </a>
                  <span><%= message.created_at.strftime("%Y-%m-%d %H:%M")%></span>
                </p>
                <p class="chat-message-body"><%= message.body %></p>
              </div>
              <div class="chat-delete">
                <% if message.user == current_user %>
                  <%= link_to message, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } do %>
                    <%= image_tag asset_path('trushbox.png'), class: 'icon-mypage' %>
                  <% end %>
                <% elsif  current_user.admin? %>
                  <%= link_to message, method: :delete, data: { confirm: '本当に削除してもよろしいですか？' } do %>
                    <%= image_tag asset_path('trushbox.png'), class: 'icon-mypage' %>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
    <div class="posts">
      <%= form_with model: @message do |f| %>
        <%= f.text_field :body, placeholder: "メッセージを入力して下さい" , size: 70, class:"form-text-field" %>
        <%= f.hidden_field :room_id, value: @room.id %>
        <%= f.submit "投稿",class: 'form-submit'%>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<div class="notice-flash">
  <% if flash[:notice] %>
    <div class="flash-message">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="flash-alert-message">
      <%= flash[:alert] %>
    </div>
  <% end %>  
</div>

app/views/shared/_follow.html.erb
<% unless current_user.id == user.id %>
  <div id="followform">
    <% if current_user.following? user %>
      <div class="follow-form-off">
        <%= link_to "フォロー外す", {controller: :users,action: :unfollow,user_id: user.id}, method: :put, class:"follow-off"%>
      </div>
    <% else %>
      <div class="follow-form-on">
        <%= link_to "フォローする", {controller: :users,action: :follow,user_id: user.id}, method: :put ,class: "follow-on" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_follow_users.html.erb
<% unless current_user.id == user.id %>
  <div id="followform">
    <% if current_user.following? user %>
      <div class="follow-form-off-users">
        <%= link_to "フォロー外す", {controller: :users,action: :unfollow,user_id: user.id}, method: :put, class:"follow-off"%>
      </div>
    <% else %>
      <div class="follow-form-on-users">
        <%= link_to "フォローする", {controller: :users,action: :follow,user_id: user.id}, method: :put ,class: "follow-on" %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="footer-copy">
    <p>&copy; 2023 Daiki-Kato</p>    
  </div>
  <div class="footer-list">
    <ul>
      <li><%= link_to "お問い合わせ", root_path, class: "footer-text" %></li>
      <li><%= link_to "利用規約", root_path, class: "footer-text" %></li>
      <li><%= link_to "プライバシーポリシー", root_path, class: "footer-text" %></li>
      <li><%= link_to "運営者情報", root_path, class: "footer-text" %></li>
    </ul>
  </div>
</div>

app/views/shared/_header.html.erb
<div class="header-home">
  <div class="logo">
    <%= link_to root_path do %>
      <%= image_tag asset_path('logo.png') %>
    <% end %>
  </div>
  <div class="nav-haeder">
    <div class="menu-li">
      <ul class="main-nav">
        <% if user_signed_in? %>
          <li class="nav-header-menu">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
          </li>
        <% else %>
          <li class="nav-header-menu">
            <%= link_to "Home", root_path %>
          </li>
           <li class="nav-header-menu">
            <%= link_to "About", about_path %>
          </li>
          <li class="nav-header-menu">
            <%= link_to "ログイン", new_user_session_path %>
          </li>
          <li class="nav-header-menu">
            <%= link_to "新規登録", new_user_registration_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <button type="button" class="btn js-btn">
    <span class="btn-line"></span>
  </button>
  <ul class="menu">
    <div class="hambueger-menu-header">
      <% if user_signed_in? %>
        <div>
          <p class="search-menu">　メニュー</p>
          <div class="hambueger-sidebar-list">
            <ul>
              <li>
                <%= link_to root_path, class: "icon-link" do %>
                  <span>Home</span>
                <% end %>
              </li>
              <li>
                <%= link_to notifications_path, class: "icon-link" do %>
                  <% if unchecked_notifications.any?%>
                    <div class="news">
                      <span class="news-span">通知未読</span> 
                    </div>
                  <% else %>
                    <span class="notification-margin">通知</span>
                  <% end %>
                <% end %>
              </li>
              <li>
                <%= link_to activities_path, class: "icon-link" do %>
                  <% if unchecked_notifications_activity.any?%>
                    <div class="news">
                      <span class="news-span">アクティビティ</span>
                    </div>
                  <% else %>
                    <span class="notification-margin">アクティビティ</span>
                  <% end %>
                <% end %>
              </li>
              <li>
                <%= link_to user_path(current_user.id), class: "icon-link" do %>
                  <span>Mypage</span>
                <% end %>
              </li>
              <li class="users-margin">
                <%= link_to users_path, class: "icon-link " do %>
                  <span>Users</span>
                <% end %>
              </li>
              <li>
                <%= link_to post_learnings_path, class: "icon-link" do %>
                  <span>学習投稿一覧</span>
                <% end %>
              </li>
              <li class="menu-list">
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </div>
        </div>
      <% else %>
        <div class="hambueger-menu">
          <div>
            <p class="search-menu">　メニュー</p>
            <div class="hambueger-sidebar-list">
              <ul>
                <li>
                  <%= link_to root_path, class: "icon-link" do %>
                    <span>Home</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to about_path, class: "icon-link" do %>
                    <span>About</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_session_path, class: "icon-link" do %>
                    <span>ログイン</span>
                  <% end %>
                </li>
                <li>
                  <%= link_to new_user_registration_path, class: "icon-link" do %>
                    <span>新規登録</span>
                  <% end %>
                </li>
              </ul>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    <div class="hambueger-menu">
      <% if user_signed_in? %>
        <div class="search-header-title"></div>
        <div class="search_form-header">
          <%= form_with url: search_keyword_path, local: true, method: :get do |f| %>
            <div class="search-form-text-header">
              <%= f.select :range, options_for_select([['ユーザー名'], ['学習名'], ['頑張ったこと']]), { prompt: '選択してください' } %>  
            </div>
            <div class="search-form-text-bottun-header">
              <div class="search-form-list-header">
                <%= f.text_field :word %>
              </div>
              <div class="search-form-submit search-text">
                <%= f.submit "検索", class: "submit-bottun" %>  
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="hambueger-menu-header">
      <% if user_signed_in? %>
        <div class="search-genre-index-header">
          <% @genres.each do |genre| %>
            <ul class="search-ul-genre-li">
              <li class="search-list-header">
                <%= link_to genre.name, search_genre_post_learnings_path(genre.id), method: :get, class: "search-genre-li-header" %>
              </li>
            </ul>
          <% end %>
        </div>
      <% end %>
    </div>
  </ul> 
  <script>
    $(function () {
      $('.js-btn').on('click', function () {
        $('.menu , .btn , .btn-line').toggleClass('open'); // メニューとバーガーの線にopenクラスをつけ外しする
      })
    })
  </script>
</div>

app/views/shared/_notification.html.erb
<% visitor = notification.visitor %>

<span>
  <%= link_to user_path(visitor) do %>
    <%= visitor.name %>
  <% end %>
  <span>さんが</span>
  <br>

  <div>
    <div>
      <% case notification.action %>
      <% when 'follow' %>
        <p>あなたをフォローしました</p>
      <% when 'favorite' %>
        <%= link_to 'あなたの投稿', notification.post_learning %>
        <p>にいいねしました</p>
      <% when 'post_comment' %>
        <% if notification.post_learning.user_id == visited.id %>
          <%= link_to "あなたの投稿", notification.post_learning %>
        <% else %>
          <div>
            <%= link_to post_path(notification.post_learning) do %>
              <%= notification.post_learning.user.name %>
            <% end %> 
            さんの投稿
          </div>
        <% end %>
        <p>にコメントしました</p>
        <%= PostComment.find_by(id: notification.post_comment_id)&.comment %>
        <hr>
      <% end %>
    </div>
    <div>
      <%= time_ago_in_words(notification.created_at).upcase %>  
    </div>
  </div>
</span>

 

app/views/shared/_post_learnings.html.erb
<div class="article-contents">
  <% @post_learnings.each do |post_learnings| %>
    <div class="article-inner">
      <div class="article-upper-half">
        <div class="upper-left">
          <div class="title-full-inner">
            <div class="eval-lower">
              <div class="article-genre">
                <div class="article-genre-title">
                  <p>ジャンル</p>
                </div>
                <div class="article-genre-name">
                  <p><%= post_learnings.genre.name %></p>
                </div>
              </div>
            </div>
          </div>
          <div class="article-time">
            <%= time_ago_in_words(post_learnings.created_at) %>前
          </div>
        </div>
        <div class="upper-right">
          <div class="article-user-image">
            <%= link_to user_path(post_learnings.user.id)  do %>
              <%= image_tag post_learnings.user.get_profile_image(100,100) %>
            <% end %>
          </div>
          <div class="article-user-name">
            <%= post_learnings.user.name %>さんが投稿しました
          </div>
        </div>
      </div>
      <div class="article-lower-half">
        <div class="article-full-lower">
          <div class="article-title"> 
            <div class="title-name-inner">
              <%= link_to post_learning_path(post_learnings.id) do %>
                <%= post_learnings.learning_name %>
              <% end %>
            </div>
          </div>
          <div class="article-effort">
            <div class="article-effort-title">
              <p>頑張ったこと</p>
            </div>
            <div class="article-effort-contents">
              <p><%= post_learnings.learning_content %></p>
            </div>
          </div>
          <div class="article-effort-image">
            <%= image_tag post_learnings.post_image.variant(resize_to_limit: [900,900]).processed if post_learnings.post_image.attached? %>
          </div>
          <div class="article-real">
            <div class="article-real-title">
              <p>学びの本音</p>
            </div>
            <div class="article-real-contents">
              <p><%= post_learnings.learning_real %></p>
            </div>
          </div>
        </div>
        <div class="article-lower-right">
          <div class="article-comments-favorites">
            <div class="article-favorites">
              <div class="show-post-favorite">
                <p>
                  <span>♥</span>いいね <%= post_learnings.favorites.count %>件
                </p>
              </div>
            </div>
            <div class="article-comments">
              <p>コメント <%= post_learnings.post_comments.count %>件</p>
            </div>
          </div>
          <div class="home-comment-inner">
            <% post_learnings.post_comments.first(4).each do |post_comment| %>
              <div class="home-comment-top">
                <div class="home-article-time">
                  <%= time_ago_in_words(post_comment.created_at) %>前
                </div>
                <div class="home-comment">
                  <div class="home-img-comment">
                    <div class="home-article-img">
                      <div class="home-user-image">
                        <p class="home-user-image-name"><%= post_comment.user.name %></p>
                        <p class="home-user-image-content"><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
                      </div>
                    </div>
                    <div class="home-comment-right">
                      <div class="home-comment-text-inner">
                        <p><%= post_comment.comment %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <div class="post-comment-more">
            <% if post_learnings.post_comments.count >= 4 %>
              <%= link_to post_learning_path(post_learnings.id) do %>
                <span>もっと見る</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate @post_learnings, class: "page" %>
</div>

app/views/shared/_post_learnings_index.html.erb
<div class="article-contents">
  <% @post_learnings.each do |post_learnings| %>
    <div class="article-inner">
      <div class="article-upper-half">
        <div class="upper-left">
          <div class="title-full-inner">
            <div class="eval-lower">
              <div class="article-genre">
                <div class="article-genre-title">
                  <p>ジャンル</p>
                </div>
                <div class="article-genre-name">
                  <p><%= post_learnings.genre.name %></p>
                </div>
              </div>
            </div>
          </div>
          <div class="article-time">
            <%= time_ago_in_words(post_learnings.created_at) %>前
          </div>
        </div>
        <div class="upper-right">
          <div class="article-user-image">
            <%= link_to user_path(post_learnings.user.id)  do %>
              <%= image_tag post_learnings.user.get_profile_image(100,100) %>
            <% end %>
          </div>
          <div class="article-user-name">
            <%= post_learnings.user.name %>さんが投稿しました
          </div>
        </div>
      </div>
      <div class="article-lower-half">
        <div class="article-full-lower">
          <div class="article-title">
            <div class="title-name-inner-index">
              <%= link_to post_learning_path(post_learnings.id) do %>
                <%= post_learnings.learning_name %>
              <% end %>
            </div>
          </div>
          <div class="article-effort">
            <div class="article-effort-title">
              <p>頑張ったこと</p>
            </div>
            <div class="article-effort-contents">
              <p><%= post_learnings.learning_content %></p>
            </div>
          </div>
          <div class="article-effort-image">
            <%= image_tag post_learnings.post_image.variant(resize_to_limit: [900,900]).processed if post_learnings.post_image.attached? %>
          </div>
          <div class="article-real">
            <div class="article-real-title">
              <p>学びの本音</p>
            </div>
            <div class="article-real-contents">
              <p><%= post_learnings.learning_real %></p>
            </div>
          </div>
        </div>
        <div class="article-lower-right">
          <div class="article-comments-favorites">
            <div class="article-favorites">
              <div class="show-post-favorite">
                <p>
                  <span>♥</span>いいね <%= post_learnings.favorites.count %>件
                </p>
              </div>
            </div>
            <div class="article-comments">
              <p>コメント <%= post_learnings.post_comments.count %>件</p>
            </div>
          </div>
          <div class="home-comment-inner">
            <% post_learnings.post_comments.first(4).each do |post_comment| %>
              <div class="home-comment-top">
                <div class="home-article-time">
                  <%= time_ago_in_words(post_comment.created_at) %>前
                </div>
                <div class="home-comment">
                  <div class="home-img-comment">
                    <div class="home-article-img">
                      <div class="home-user-image">
                        <p class="home-user-image-name"><%= post_comment.user.name %></p>
                        <p class="home-user-image-content"><%= image_tag post_comment.user.get_profile_image(100,100) %></p>
                      </div>
                    </div>
                    <div class="home-comment-right">
                      <div class="home-comment-text-inner">
                        <p><%= post_comment.comment %></p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
          <div class="post-comment-more">
            <% if post_learnings.post_comments.count >= 4 %>
              <%= link_to post_learning_path(post_learnings.id) do %>
                <span>もっと見る</span>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate @post_learnings, class: "page" %>  
</div>
    

app/views/shared/_sidebar.html.erb
<div class="sidebar-full">
  <div class="sidebar">
  <div class="sidebar-contents">
    <div class="sidebar-menu">
      <p>　メニュー</p>
      <div class="sidebar-list">
        <ul>
          <li>
            <%= link_to home_path, class: "home-link" do %>
              <%= image_tag '/assets/home_icon.png', class:'icon' %>
              <span>Home</span>
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: "icon-link" do %>
              <%= image_tag '/assets/users_icon.jpeg', class:'icon' %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to post_learnings_path, class: "icon-link" do %>
              <%= image_tag '/assets/article_icon.png', class:'icon' %>
              <span>学習投稿一覧</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="sidebar-btn">
    <%= link_to "投稿する", new_post_learning_path, class: "sidebar-btn-link" %>
  </div>
  <div class="sidebar-contents">
    <div class="sidebar-serch">
      <p class="search-key">　キーワードで探す</p>
        <div class="sidebar-list">
          <%= form_tag(search_post_learnings_path,:method => 'get') do %>
            <div class="search-form">
              <%= text_field_tag :search %>
              <%= submit_tag '検索', :name => nil %>
            </div>
          <% end %>
          <p class="search-genre">　ジャンルで探す</p>
          <% @genres.each do |genre| %>
            <ul>
              <li>
                <%= link_to genre.name, search_post_learnings_path(genre.id), method: :get %>
              </li>
            </ul>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar_left.html.erb
<div class="sidebar-full">
  <div class="sidebar">
    <% if user_signed_in? %>
    <div class="sidebar-contents">
      <div class="sidebar-serch">
        <p class="search-key">　キーワードで探す</p>
        <div class="sidebar-list">
          <div class="search_form">
            <%= form_with url: search_keyword_path, local: true, method: :get do |f| %>
              <div class="search-form-text">
                <%= f.select :range, options_for_select([['ユーザー名'], ['学習名'], ['頑張ったこと']]), { prompt: '選択してください' } %>  
              </div>
              <div class="search-form-text-bottun">
                <div class="search-form-list">
                  <%= f.text_field :word %>
                </div>
                <div class="search-form-submit">
                  <%= f.submit "検索", class: "submit-bottun" %>  
                </div>
              </div>
            <% end %>
          </div>
          <div class="search-genre-index">
            <p class="search-genre">　ジャンルで探す</p>
            <% @genres.each do |genre| %>
              <ul>
                <li class="search-list">
                  <%= link_to genre.name, search_genre_post_learnings_path(genre.id), method: :get, class: "search-genre-li" %>
                </li>
              </ul>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <% end %>
    <div class="sidebar-left-btn">
      <p>今日もお疲れ様です！</p>
       <div class="sidebar-btn">
        <%= link_to "投稿する", new_post_learning_path, class: "sidebar-btn-link" %>
      </div>
      <div class="sidebar-btn-sp">
        <%= link_to "＋", new_post_learning_path, class: "sidebar-btn-link-sp" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_sidebar_right.html.erb
<div class="sidebar-content">
  <% if user_signed_in? %>
    <div class="sidebar-menu">
      <p>　メニュー</p>
      <div class="sidebar-list">
        <ul>
          <li>
            <%= link_to root_path, class: "home-link" do %>
              <%= image_tag asset_path('home_icon.png'), class: 'icon' %>
              <span>Home</span>
            <% end %>
          </li>
          <li>
            <%= link_to notifications_path, class: "notification-link" do %>
              <% if unchecked_notifications.any?%>
                <div class="news">
                  <%= image_tag asset_path('notification.png'), class: 'icon' %>
                  <span class="news-span">通知未読</span> 
                </div>
              <% else %>
                <%= image_tag asset_path('notification.png'), class: 'icon' %>
                <span class="notification-margin">通知</span>
              <% end %>
            <% end %>
          </li>
          <li>
            <%= link_to activities_path, class: "notification-link" do %>
              <% if unchecked_notifications_activity.any?%>
                <div class="news">
                  <%= image_tag asset_path('activity.png'), class: 'icon' %>
                  <span class="news-span">アクティビティ</span>
                </div>
              <% else %>
                <%= image_tag asset_path('activity.png'), class: 'icon' %>
                <span class="notification-margin">アクティビティ</span>
              <% end %>
            <% end %>
          </li>
          <li>
            <%= link_to user_path(current_user.id), class: "icon-link" do %>
              <%= image_tag asset_path('mypage_icon.png'), class: 'icon' %>
              <span>Mypage</span>
            <% end %>
          </li>
          <li>
            <%= link_to users_path, class: "icon-link" do %>
              <%= image_tag asset_path('users_icon.jpeg'), class: 'icon' %>
              <span>Users</span>
            <% end %>
          </li>
          <li>
            <%= link_to post_learnings_path, class: "icon-link" do %>
              <%= image_tag asset_path('article_icon.png'), class: 'icon' %>
              <span>学習投稿一覧</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_users.html.erb
<% @users.each do |users| %>
  <div class="users-inner">
    <div class="users-full">
      <div class="article-users-image">
        <%= image_tag users.get_profile_image(180,180) %>
      </div>
      <div class="users-middle">
        <div class="users-title-name">
          <p>ユーザー名</p>
        </div>
        <div class="article-users-name">
          <%= link_to user_path(users.id)  do %>
            <%= users.name %>
          <% end %>
        </div>
        <div class="users-follow-list">
          <% unless current_user.admin? %>
            <%= render 'shared/follow_users', user: users %>
          <% end %>
        </div>
      </div>
      <div class="users-right">
        <div class="users-title-introduction">
          <p>自己紹介</p>
        </div>
        <div class="article-users-introduction">
          <p><%= users.introduction %></p>
        </div>
      </div>  
    </div>
  </div>
<% end %>
<%= paginate @users %> 