config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: "homes#home"
  get "about" => "homes#about"

  get "search/keyword" => "searches#search_keyword"

  resources :post_learnings do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
    get :search_genre, on: :collection
  end

  resources :post_learnings
  namespace :admin do
    resources :post_learnings, only: [:index, :new, :create, :show,  :edit, :destroy]
  end

  post "post_learnings/new" => "post_learnings#new"

  get "post_learnings/:id/post_comments" => "post_learnings#show"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
  }
  
  devise_scope :user do
    post "users/guest_sign_in" => "users/sessions#guest_sign_in"
    get "users/guest_sign_in" => "users/sessions#guest_sign_in"
  end

  put 'users/follow/:user_id' => 'users#follow'
  put 'users/unfollow/:user_id' => 'users#unfollow'
  get 'users/follow_list/:user_id' =>'users#follow_list'
  get 'users/follower_list/:user_id' => 'users#follower_list'

  resources :tags, only: [:index]
  resources :users, only: [:index, :show, :edit, :update, :destroy]

  resources :genres

  resources :messages, only: [:create, :destroy]
  resources :rooms, only: [:create, :show]

  resources :notifications, only: [:index]  do
    collection do
      delete 'destroy_all'
    end
  end
  
  resources :activities, only: [:index] do 
    collection do
      delete 'destroy_all'
    end
  end
  
  resources :contacts, only: [:new, :create]
 
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = current_user.active_notifications.page(params[:page]).per(20)
    @activities.where(checked: false).each do |activity|
     activity.update(checked: true)
    end
    @genres = Genre.all
  end
  
   def destroy_all
    @activities = current_user.active_notifications.destroy_all
    flash[:notice] = "アクティビティを削除しました"
  	 redirect_to request.referer 
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_activity.html.erb
<% visitor = activity.visitor %>
<% visited = activity.visited %>

<div class="notification-text-time">
  <p>
    <%= time_ago_in_words(activity.created_at).upcase %>前  
  </p>
</div>
<div class="notification-content activity-margin activity-margin-text">
  <div class="notification-text-content activity-margin-inner">
    <% case activity.action
    when 'follow' %>
      <div class="notification-comment-user-content-activity">
        <div>
          <div>
            <%= link_to user_path(visited), class: "article-notification-image" do %>
              <%= image_tag visited.get_profile_image(100,100) %>
            <% end %>  
          </div>
          <div>
            <%= link_to user_path(visited), class: "article-notification-image" do %>
              <strong>
                <%= visited.name %>
              </strong>
            <% end %> 
          </div>
        </div>
        <div class="notification-comment-name-content-activity">
          さんをフォローしました
        </div>
      </div>
    <% when 'favorite' %>
      <div class="notification-comment-user-content-activity">
        <div>
          <div>
            <%= link_to user_path(visited), class: "article-notification-image" do %>
              <%= image_tag activity.post_learning.user.get_profile_image(100,100) %>
            <% end %>  
          </div>
          <div>
            <%= link_to post_learning_path(activity.post_learning), class: "article-notification-image" do %>
              <strong>
                <%= activity.post_learning.user.name %>
              </strong>
            <% end %>
          </div>
        </div>
        <div class="notification-comment-name-content-activity">
          さんの投稿にいいねしました
        </div>
      </div>
    <% when 'post_comment' %>
      <% if activity.post_learning.user_id == visitor.id %>
        <div class="notification-comment-my-content-activity">
        　<%= link_to "あなたの投稿", activity.post_learning %>にコメントしました  
        </div>
      <% else %>  
        <div class="notification-comment-user-content">
          <div>
            <%= link_to user_path(visited), class: "article-notification-image" do %>
              <%= image_tag activity.post_learning.user.get_profile_image(100,100) %>
            <% end %>
          </div>
          <div class=notification-comment-name-content>
            <%= link_to post_learning_path(activity.post_learning), class: "article-notification-image" do %>
              <strong>
                <%= activity.post_learning.user.name %>
              </strong>
            <% end %>
            さんの投稿にコメントしました
          </div>
        </div>
      <% end %>
      <p class="notification-comment"><%= PostComment.find_by(id: activity.post_comment_id)&.comment %></p>
    <% when 'dm' %>
    <div class="notification-favorite-content-inner-activity">
      <%= link_to user_path(visited), class: "article-notification-image" do %>
        <strong>
          <%= visited.name %>
        </strong>
      <% end %>
      さんにDMを送りました
    </div>
      <p class="notification-comment-dm">
        <%= truncate(activity.message.body, length: 20, omission: '... (一部表示)') %>
        <%= link_to room_path(activity.room) do %>
          <h4 class="dm-move">DMの送信画面に移動</h4>
        <% end %>
      </p>
    <% end %>
  </div>
</div>
<hr>

app/views/activities/index.html.erb
<div class="first-home-view">
  <%= render 'shared/header' %>
  <%= render 'shared/flash' %>
  <div class="result-notifications-main-full">
    <div class="result-activities-name-title">
      <p>アクティビティ</p>
    </div>
  </div>
  <div class="top-contents">
    <aside class="sidebar_left">
      <%= render 'shared/sidebar_left' %>
    </aside>
    <article class="users-article">
      <div class="destroy_all_notifications">
        <%= link_to destroy_all_activities_path, method: :delete do %>
          <h7>全削除</h7>
        <% end %>
      </div>
      <hr>
      <% if @activities.exists? %>
        <% @activities.each do |activity| %>
          <div class="users-index">
            <%= render 'activities/activity', activity: activity %>
          </div>
        <% end %>
      <% else %>
        <p class="no-notification">アクティビティはありません</p>
      <% end %>
      <%= paginate @activities, class: "page" %>
    </article>
    <aside class="sidebar_right">
      <%= render 'shared/sidebar_right' %>
    </aside>
  </div>
</div>
<%= render 'shared/footer' %>